files:
  - source: /shared/src/commonMain/resources/MR/base/strings.xml
    translation: /shared/src/commonMain/resources/MR/%android_code%/%original_file_name%
preserve_hierarchy: true
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
